### ISSUE TITLE
OS Error: Failed to parse: https://chromedriver.storage.googleapis.com/LATEST_RELEASE_89.0.4389

### ISSUE THREAD

**Issue by paulfeakins** [creativeJoe007/google-leads-scraper#2]
Fails as below:
```
python3 main.py "test" --start=1 --stop=5 --file="emails.csv"

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 89.0.4389
[WDM] - Get LATEST driver version for 89.0.4389

 OS Error: Failed to parse: https://chromedriver.storage.googleapis.com/LATEST_RELEASE_89.0.4389
```

**Comment by creativeJoe007** [comment]
Hello,

I will look into it and see what went wrong

When I do, I will reachout to you.

Do you mind providing a screenshot though?

**Comment by paulfeakins** [comment]
Hi,

I'm not sure what extra info a screenshot would give you, the output is exactly as above.

I'm on Linux Mint:
Kernel: 5.4.0-66-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Xfce 4.14.2 
           tk: Gtk 3.24.13 wm: xfwm4 dm: LightDM Distro: Linux Mint 20.1 Ulyssa 
           base: Ubuntu 20.04 focal

**Comment by creativeJoe007** [comment]
<img width="568" alt="Screenshot 2021-03-15 at 15 32 49" src="https://user-images.githubusercontent.com/52638039/111169942-b81cf100-85a3-11eb-8260-bdfb17e6ae5f.png">

**Comment by paulfeakins** [comment]
So you're getting the error too?

**Comment by creativeJoe007** [comment]
No, that's not an exact error, that's it working.

**Comment by paulfeakins** [comment]
Thanks for the reply. I had tried to install a few similar tools and it turns out one of them had caused me to install loads of python modules, some of which seem to have broken this and another of the tools.

After clearing out a load of modules, this now runs nicely, so all good to close this issue - thanks!

**Comment by creativeJoe007** [comment]
Oh, glad it's been resolved. This one uses its own env so it doesn't invade
your other projects.

**Comment by paulfeakins** [comment]
Yes that's very wise, unfortunately the other project didn't, and I didn't create one *facepalm*

**Comment by creativeJoe007** [comment]
Lol, it's all good. Glad it worked out just fine.
