### ISSUE TITLE
Unable to locate element

### ISSUE THREAD

**Issue by Twibow** [creativeJoe007/google-leads-scraper#3]
Hello !

I've a Selenium Error during the scraping process : 
`Selenium error: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.tF2Cxc"}
  (Session info: headless chrome=91.0.4472.114)
  
 Selenium error: Message: no such element: Unable to locate element: {"method":"css selector","selector":"span.aCOpRe"}
  (Session info: headless chrome=91.0.4472.114)

 Selenium error: Message: no such element: Unable to locate element: {"method":"css selector","selector":"span.aCOpRe"}
  (Session info: headless chrome=91.0.4472.114)

...
`

Maybe a Google CSS skeleton modification.

**Comment by creativeJoe007** [comment]
Were you able to scrap or the scraper stopped when it encountered that error?

**Comment by Twibow** [comment]
The script returns this error for each search without stopping. If the limit is set at 10 for example, the error message appears 10 times.

**Comment by creativeJoe007** [comment]
Oh, I see.

I will take a look at it today, once I step out of work.

**Comment by creativeJoe007** [comment]
Hello,
Apologies for the delay, I have fixed this issue and made a push. Kindly pull and try again

**Comment by creativeJoe** [comment]
It's been 15 days and I haven't gotten feedback if my last push fixed the issue in question. I will be closing this issue, if the issue persists do not hesitate to reopen it.

**Comment by creativeJoe007** [comment]
It's been 15 days and I haven't gotten feedback if my last push fixed the issue in question. I will be closing this issue, if the issue persists do not hesitate to reopen it.

**Comment by wch160030** [comment]
I'm getting the exact same issue. What was the fix
