### ISSUE TITLE
ModuleNotFoundError: No module named 'webdriver_manager.utils'

### ISSUE THREAD

**Issue by Davidjrsomper** [creativeJoe007/google-leads-scraper#5]
Webdriver manager is already satisfied (Requirement already satisfied: webdriver_manager in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (3.7.0))

however I am receiving the error 

from webdriver_manager.utils import ChromeType
ModuleNotFoundError: No module named 'webdriver_manager.utils'

**Comment by creativeJoe007** [comment]
Hi David,

Kindly pull as I have merged a pull request that does fix this and I'm making changes to the requirements.txt to ensure version 3.7.1 is installed and not the older version that doesn't support ".core.utils"

**Comment by creativeJoe007** [comment]
Sorry for the delay as well, been a busy week

**Comment by creativeJoe007** [comment]
I will be closing this issue now as I have merged a pr that fixes this problem but haven't gotten any feedback
