### ISSUE TITLE
Selenium error: Message: no such element

### ISSUE THREAD

**Issue by hamzaaitbrik** [creativeJoe007/google-leads-scraper#6]
I get this error while I try to pull data:
Selenium error: Message: no such element: Unable to locate element: {"method":"css selector","selector":"div.tF2Cxc"}
  (Session info: headless chrome=103.0.5060.114)
The error repeats exactly the number of pages I input to be scraped.
Do you have any idea what could cause such error? Also, is there any fix for it?

**Comment by creativeJoe007** [comment]
I'll look into it

**Comment by creativeJoe007** [comment]
Resolved, kindly retry.

Sorry for the late fix, I was busy at work

**Comment by creativeJoe007** [comment]
I will be closing this issue as I haven't heard from you

**Comment by hamzaaitbrik** [comment]
it now works! thanks for your replies. I thought this scrapes emails thou.

**Comment by creativeJoe007** [comment]
it does extract email and mobile numbers

**Comment by hamzaaitbrik** [comment]
got nothing.. just random keywords on a csv file
