### ISSUE TITLE
program closes

### ISSUE THREAD

**Issue by bdkw** [creativeJoe007/google-leads-scraper#8]
whenever i try to run the program closes itself and opens the code in vs code
![image](https://user-images.githubusercontent.com/50743953/206910938-aa6eac9d-ccaf-40d5-b7c4-a1f7aba68f36.png)

**Comment by creativeJoe007** [comment]
How did you attempt to run the script as it looks like you are using Windows

**Comment by creativeJoe007** [comment]
Closed as no feedback
